config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :products, only: [:index, :show, :search]
  match "/admin/coupons/showcoupons" => "admin/coupons#showcoupons", via: :get, as: "admin_coupons_showcoupons"

  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
  end

  as :product do
    delete "products/:id" => "products#destroy"
  end
  root to: "products#index"
  get "/help", to: "detail_pages#help"
  get "/about", to: "detail_pages#about"
  get "/contact", to: "detail_pages#contact"
  get "/search", to: "products#search"
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true

    if user.present?  # additional permissions for logged in users (they can read their own posts)
      can :read, Post, user_id: user.id

      if user.admin?  # additional permissions for administrators
        can :read, Post
      end
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :update_subtotal, :update_total
  # tong tien
  def subtotal
    order_items.collect { |item| item.valid? ? (item.quantity * item.unit_price) : 0 }.sum
  end

  def total
    order_items.collect { |item| item.valid? ? item.quantity : 0 }.sum
  end

# private

  def update_subtotal
    self[:subtotal] = subtotal
  end

  def update_total
    self[:total] = total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present
  before_save :finalize

  def unit_price
    product.price
  end

  def total_price
    unit_price * quantity
  end

private

  def product_present
    return if product

    errors.add(:product, 'is not valid or is not active.')
  end

  def order_present
    return if order

    errors.add(:order, 'is not a valid order.')
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :category
  # belongs_to :user
  has_many :order_items
  validates :title, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :price, presence: true
  has_one_attached :image
  validates :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  scope :recently_ordered, -> { joins(:order_items).where("order_items.created_at > ?", 3.months.ago).distinct.group("products.id").order("SUM(order_items.quantity) DESC") }

  def display_image
    self.image.variant(resize: "150 x 150")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_order
  # to call anywhere
  def current_order
    return Order.find(session[:order_id]) if session[:order_id]

    Order.new
  end
  # def current_order
  #   @current_order ||= Order.find_by(id: session[:order_id]) || Order.new
  # end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/detail_pages_controller.rb
class DetailPagesController < ApplicationController
  def home; end

  def show; end

  def help; end

  def contact; end

  def about; end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  def create
    @order_item = @order.order_items.new(order_item_params)
    return session[:order_id] = @order.id if @order.save

    redirect_to products_path, notice: "Order could not be saved. #{@order.errors.full_messages.join(', ')}"
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update(order_item_params) ? flash[:success] = 'Order item updated successfully.' : flash[:error] = "Order item could not be updated. #{@order_item.errors.full_messages.join(", ")}"
    set_order_again
    redirect_to cart_path
  end

  def destroy
    @order_items = @order.order_items
    @order_items.find(params[:id])&.destroy ? flash[:success] = 'The product has been successfully removed from your cart.' : flash[:error] = 'Something went wrong. The product could not be removed from your cart.'
    redirect_to cart_path
    return set_order_again unless @order_items.empty?

    @order.destroy
    reset_session
  end

  # def destroy
  #   @order_items = @order.order_items
  #   if @order_items.find(params[:id])&.destroy && @order_items.size == 0
  #     @order.destroy
  #     reset_session
  #   end
  # end

private

  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end

  def set_order
    @order = current_order
  end

  def set_order_again
    @order.update_total
    @order.update_subtotal
    @order.save
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :search, only: [:index]

  # GET /products or /products.json
  def index
    # @products = Product.all.order(id: :desc).paginate(page: params[:page], per_page: Settings.per_page_max)
    @pop_products = Product.recently_ordered.limit(Settings.limit).paginate(page: params[:page], per_page: Settings.per_page_min)
    # @order_item = current_order.order_items.new
    # @products = Product.all.order(id: :desc).paginate(page: params[:page], per_page: Settings.per_page_max)
  end

  # GET /products/1 or /products/1.json
  def show; end

  def search
    @order_item = current_order.order_items.new
    search_term = params[:search] || ""
    @products = Product.where("title LIKE ?", "%" + search_term + "%").order(id: :desc).paginate(page: params[:page], per_page: Settings.per_page_max)
    if @products.empty?
      flash[:error] = "Product was not found."
      redirect_to products_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:category_id, :title, :price, :thumbnail, :description, :image)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/detail_pages_helper.rb
module DetailPagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <h1> Total Price: <%= number_to_currency current_order.subtotal %> </h1>
<% end %>

app/views/layouts/_admin.html.erb
<li><%= link_to t(".user_list"), users_path %></li>
<li><%= link_to t(".stastitics"), "#" %></li>
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= @current_user.name %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("update"), edit_user_path(current_user) %></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), logout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_customer.html.erb
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= current_user.email %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to "Lich su mua hang"%></li>
    <li><%= link_to t("profile")%></li>
    <li><%= link_to t("update")%></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), signout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_employee.html.erb
<li><%= link_to t(".add_book"), new_book_path %></li>
<li><%= link_to t(".order_list"), orders_path %></li>
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= @current_user.name %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to t("history_order"), "#" %></li>
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("update"), edit_user_path(current_user) %></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), logout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="clearfix"></div>
    <div class="footer-info w3-agileits-info">
      <div class="col-sm-5 address-right">
        <div class="col-xs-6 footer-grids">
          <h3>Categories</h3>
          <ul>
            <li>
              <a href="#">Grocery</a>
            </li>
          </ul>
        </div>
        <div class="col-xs-6 footer-grids agile-secomk">
          <ul>
            <li>
              <a href="#">Snacks & Beverages</a>
            </li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </div>
      <!-- //footer categories -->
      <!-- quick links -->
      <div class="col-sm-5 address-right">
        <div class="col-xs-6 footer-grids">
          <h3>Quick Links</h3>
          <ul>
            <li>
              <%= link_to t("about_title"), about_path %>
              <li><%= link_to t("contact_title"), contact_path%></li>
              <li><%= link_to t("help_title"), help_path%></li>
              <li><%= link_to t("lang_en"), locale:"en" %></li>
              <li><%= link_to t("lang_vi"), locale:"vi" %></li>
            </li>
          </ul>
        </div>
        <div class="col-xs-6 footer-grids">
          <h3>Get in Touch</h3>
          <ul>
            <li>
              <i class="glyphicon glyphicon-map-marker"></i> 123 Sebastian, USA.</li>
            <li>
              <i class="glyphicon glyphicon-earphone"></i> 333 222 3333 </li>
            <li>
              <i class="glyphicon glyphicon-phone"></i> +222 11 4444 </li>
            <li>
              <i class="glyphicon glyphicon-envelope"></i>
              <a href="#"> mail@example.com</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- //quick links -->
      <!-- social icons -->
      <div class="col-sm-2 footer-grids  w3l-socialmk">
        <h3>Follow Us on</h3>
        <div class="social">
          <ul>
            <li>
              <%= link_to image_tag("facebook.png", all: "", class: "icon-footer") %>
            </li>
            <li>
              <%= link_to image_tag("twiter.png", all: "", class: "icon-footer") %>
            </li>
            <li>
              <%= link_to image_tag("google-plus.png", all: "", class: "icon-footer") %>
            </li>
          </ul>
        </div>
        <div class="agileits_app-devices">
          <h5>Download the App</h5>
          <a href="#">
            <%= link_to image_tag("google-play.png", all: "") %>
          </a>
          <a href="#">
            <%= link_to image_tag("app-store.png", all: "") %>
          </a>
          <div class="clearfix"> </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="agile-sometext">
      <div class="sub-some child-momu">
        <h5>Payment Method</h5>
        <ul>
          <li>
            <%= link_to image_tag("pay2.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay1.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay3.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay7.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay8.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay9.png", all: "") %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-bot">
  <div class="header-bot_inner_wthreeinfo_header_mid">
    <!-- header-bot-->
    <div class="col-md-3 logo_agile">
      <h1>
        <%= link_to root_path, class: "home" do %>
          <span>B</span>ook
          <span>S</span>tore
          <%= link_to image_tag("logo2.png"), root_path %>
        <% end %>
      </h1>
    </div>
    <!-- header-bot -->
    <div class="col-md-9 header">
      <!-- header lists -->
      <ul>
        <li>
          <a class="aa" href="#">
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Shop Locator</a>
        </li>
        <li>
          <a href="#" data-toggle="modal" data-target="#myModal1">
            <span class="fa fa-truck" aria-hidden="true"></span>Track Order</a>
        </li>
        <li>
          <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 001 234 5678
        </li>
        <% if user_signed_in? %>
          <%= render "layouts/customer" %>
        <% else %>
          <li>
            <%= link_to  signin_path, class: "btn btn-success" do %>
              <span class="glyphicon glyphicon-log-in"></span>
              <%= t("sign_in") %>
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-edit"></span>
              <%= t("sign_up") %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div class='search_button'>
        <div class="agileits_search">
          <%= form_tag search_path, method: :get, remote: true do |f| %>
            <%= text_field_tag :search, params[:search], placeholder: "Book name, author..." %>
            <%= button_to "", name: nil, class: "btn btn-default", "aria-label" => "Left Align" do %>
              <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
            <% end %>
          <% end %>
        </div>
        <div class="top_nav_right">
          <div class="wthreecartaits wthreecartaits2 cart cart box_1">
            <%= link_to cart_path, class: "btn btn-info btn-lg" do %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
              <%= t("cart") %>
            <% end %>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="ban-top">
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav menu__list">
            <li class="">
              <%= link_to t("home_title"), root_path, class: "nav-stylehead" %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-stylehead" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">English Books
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu multi-column columns-3">
                <div class="agile_inner_drop_nav_info">
                  <div class="col-sm-4 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li>
                        <a href="#">Category 1</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-4 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li>
                        <a href="#">Category 2</a>
                      </li>
                    </ul>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-stylehead" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vietnamese Books
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu multi-column columns-3">
                <div class="agile_inner_drop_nav_info">
                  <div class="col-sm-6 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li>
                        <a href="#">Vietnamese Book 1</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-6 multi-gd-img">
                    <ul class="multi-column-dropdown">
                      <li>
                        <a href="#">Vietnamese Book 2</a>
                      </li>
                    </ul>
                  </div>
                  <div class="clearfix"></div>
                </div>
              </ul>
            </li>
            <li class="">
              <a class="nav-stylehead" href="#">Faqs</a>
            </li>
            <li class="dropdown">
              <a class="nav-stylehead dropdown-toggle" href="#" data-toggle="dropdown">Pages
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu agile_short_dropdown">
                <li>
                  <a href="#">Web Icons</a>
                </li>
                <li>
                  <a href="#">Typography</a>
                </li>
              </ul>
            </li>
            <li class="">
              <%= link_to t("about_title"), about_path, class: "nav-stylehead" %>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>

app/views/products/_product.html.erb
<div class="col-md-4 product-men">
  <div class="men-pro-item simpleCart_shelfItem">
    <div class="men-thumb-item">
      <%= image_tag product.display_image if product.image.attached? %>
      <div class="men-cart-pro">
        <div class="inner-men-cart-pro">
          <%= link_to "Quick View", product_path(product, :id),
              class: "link-product-add-cart"%>
        </div>
      </div>
      <span class="product-new-top">New</span>
    </div>
    <div class="item-info-product">
      <h4>
        <p><%= product.title %></p>
      </h4>
    </div>
    <div class="info-product-price">
      <h2>
        <strong> 
          <p><%= product.price %> &#36; </p>
        </h2>
      </div>
      <%= form_for @order_item, remote: true, :html => { :onsubmit => "showPopup()" } do |f| %>
        <div class="input-group">
          <%= f.hidden_field :quantity, value: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <%= f.submit "Add to Cart" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/products/index.html.erb
<% provide :title, t("home_title") %>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= link_to image_tag("jumbotronbackground.jpg", style: "width: 100%;", alt: "Banner 1")%>
    </div>
    <div class="item">
      <%= link_to image_tag("banner2.jpg", style: "width: 100%;", alt: "Banner 2")%>
    </div>
    <div class="item">
      <%= link_to image_tag("banner3.jpg", style: "width: 100%;", alt: "Banner 3")%>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- //banner -->
<!-- top Products -->
<div class="ads-grid">
  <div class="container">
    <!-- tittle heading -->
    <!-- //tittle heading -->
    <!-- product left -->
    <div class="side-bar col-md-3">
      <div class="search-hotel">
        <h3 class="agileits-sear-head">Search Here..</h3>
      </div>
      <div>
        <div class='search_button nogap'>
          <div class="agileits_search">
            <%= form_tag search_path, method: :get, remote: true do |f| %>
              <%= text_field_tag :search, params[:search], placeholder: "Book name, author..." %>
              <%= button_to "", name: nil, class: "btn btn-default", "aria-label" => "Left Align" do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="range">
        <h3 class="agileits-sear-head">Categories</h3>
        <ul class="dropdown-menu6">
        </ul>
      </div>
      <!-- price range -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Price range</h3>
        <ul class="dropdown-menu6">
          <li>
            <input type="checkbox" class="checked">
            <span class="span">0$ - 20$</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">20$ - 50$</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">50$ - 100$</span>
          </li>
        </ul>
      </div>
      <!-- //price range -->
      <!-- food preference -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Food Preference</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">Vegetarian</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">Non-Vegetarian</span>
          </li>
        </ul>
      </div>
      <!-- //food preference -->
      <!-- discounts -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Discount</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">5% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">10% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">20% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">30% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">50% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">60% or More</span>
          </li>
        </ul>
      </div>
      <!-- //discounts -->
      <!-- reviews -->
      <div class="customer-rev left-side">
        <h3 class="agileits-sear-head">Customer Review</h3>
        <ul>
          <li>
            <a href="#">
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <span>5.0</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- //reviews -->
      <!-- cuisine -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Cuisine</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">South American</span>
          </li>
        </ul>
      </div>
      <!-- //cuisine -->
      <!-- deals -->
      <div class="deal-leftmk left-side">
        <h3 class="agileits-sear-head">Special Deals</h3>
        <div class="special-sec1">
          <div>
            <%= link_to image_tag("2.jpg", alt: " ", class: "special-image") %>
          </div>
          <div>
            <h3>Lay's Potato Chips</h3>
            <a href="#">$18.00</a>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- //deals -->
    </div>
    <!-- //product left -->
    <!-- product right -->
    <div class="agileinfo-ads-display col-md-9">
      <div class="wrapper">
        <!-- first section (nuts) -->
        <div class="product-sec1">
          <h3 class="heading-tittle">All Books</h3>
          <% if @products&.any? %>
            <ul><%= render @products%></ul>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <div class="agileinfo-ads-display col-md-9">
      <div class="wrapper">
        <!-- first section (nuts) -->
        <div class="product-sec1">
          <h3 class="heading-tittle">Popular books</h3>
          <% if @pop_products&.any? %>
            <ul><%= render @pop_products %></ul>
            <p><%= will_paginate @pop_products %></p>
          <% end %>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <!-- //product right -->
  </div>
</div>
<!-- //top products -->
<!-- special offers -->
<div class="featured-section" id="projects">
  <div class="container">
    <!-- tittle heading -->
    <h3 class="tittle-w3l">Special Offers
      <span class="heading-style">
        <i></i>
        <i></i>
        <i></i>
      </span>
    </h3>
    <!-- //tittle heading -->
    <div class="content-bottom-in">
      <ul id="flexiselDemo1">
        <% 4.times do %>
          <li class="slide-footer">
            <div class="w3l-specilamk">
              <div class="speioffer-agile">
                <%= link_to image_tag("3.jpg", alt: " ", class: "slide_foot") %>
              </div>
              <div class="product-name-w3l">
                <h4>
                  <a href="#">Aashirvaad, 5g</a>
                </h4>
                <div class="w3l-pricehkj">
                  <h6>$220.00</h6>
                  <p>Save $40.00</p>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                  <input type="submit" name="submit" value="Add to cart" class="button" />
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div id="products-show">
     <div class="products-show-left">
        <% if @product.image.attached? %>
        <%= image_tag(@product.image) %>
        <%end%>
    </div>
    <h2><%=@product.title%></h2>
    <div class="products-show-right">
        <ul>
            <li><strong>Title: </strong><%= @product.title %></li>
            <li><strong>Category: </strong><%= @product.category_id %></li>
            <li><strong>Description: </strong><%= @product.description %></li>
            <li><strong>Price: </strong><%= @product.price %></li>
        </ul>
      <%= link_to 'Edit', admin_product_path(@product) %> |
      <%= link_to 'Back', products_path %>
</div>